name = "mito-api"
main = "src/index.js"
compatibility_date = "2023-10-02"

[vars]
ENVIRONMENT = "production"

# When deploying via GitHub, you'll need to create a new D1 database
# and update this binding with your new database ID in the Cloudflare dashboard
[[d1_databases]]
binding = "DB"
database_name = "mito-holders"
# The database_id will be populated by Cloudflare when you create and bind the database
